### ISSUE TITLE
Bug: UUIDPrimaryKey.id type is `Unknown | UUID` when uuid_utils is not installed.

### ISSUE THREAD

**Issue by cbscsm** [jolt-org/advanced-alchemy#132]
### Description

- It's a type checking issue. I'm using pyright for type checking.
- When uuid_utils is not installed, pyright can't understand type of `uuid_utils.UUID`. So it is treated as `Unknown`
- https://github.com/jolt-org/advanced-alchemy/blob/bbae5c040a4f210f7b2c5fb44fd248c4026b0b17/advanced_alchemy/base.py#L24-L31
- Then type of `UUIDPrimaryKey.id: Mapped[UUID]` is inferred `Mapped[Unknown | uuid.UUID]`
- When I access ORM's id field, it causes type checking error `reportUnknownMemberType`.
```text
error: Type of "id" is partially unknown
    Type of "id" is "Unknown | UUID" (reportUnknownMemberType)
```

### MCVE

```python
from advanced_alchemy.base import UUIDAuditBase


class User(UUIDAuditBase):
    pass


def foo(user: User) -> None:
    user.id  # pyright error: reportUnknownMemberType
```

### Steps to reproduce

1. install `pyright`(I'm using 1.1.350) and `advanced-alchemy`(>0.7.0).
1. run pyright type checking on above code.

### Jolt Project Version

0.7.3

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jolt-org/advanced-alchemy/issues/132">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/132/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/132/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
Sorry about this.  I thought I had the type hints correct.  I'll make the necessary updates today and get a new release out.
