### ISSUE TITLE
Bug: CollectionFilter returns all entries if values is empty

### ISSUE THREAD

**Issue by audiovention** [jolt-org/advanced-alchemy#51]
### Description

Basically what the title says, when initializing a CollectionFilter with an empty list, the resulting query returns all entries instead of no entries, which I'd expect. 
I know it's a special case and needs to be handled differently, but this seems very inconsistent behaviour. 
Here's the specific line which leads to that bug (currently in advanced-alchemy project, although the code is unchanged since it was part of litestar)
https://github.com/jolt-org/advanced-alchemy/blob/46d3e7acbc7a391b4bab06fe7e64f3d45826270a/advanced_alchemy/repository/_async.py#L1109

Issue was first raised on the litestar discord
The bug is replicated in the sync repo as well

### Jolt Project Version

master

### Platform

- [X] Linux
- [X] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jolt-org/advanced-alchemy/issues/51">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/51/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/51/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
@audiovention thanks for reporting this.  Did you want to open a PR for this?  If not, I'll try to work something in over the weekend.

**Comment by audiovention** [comment]
I can try something in the coming week, won't be this weekend though

**Comment by provinzkraut** [comment]
Thinking what the best way to handle this would be. Since all the filters you can pass in are `AND`ed (for now), if there's an empty `CollectionFilter`, the result will always be empty as well, so we could in theory just return an empty list straight away without ever actually touching the database (or just produce an always empty query so we don't alter the current flow of the filter logic too much).

The other option would be to just let SQLAlchemy handle it normally.

@cofin thoughts?

**Comment by cofin** [comment]
Not even hitting the database is probably not a bad idea.  I was originally thinking that we could just add a `where 1=-1` filter to the query when we detect an empty list, but maybe not even running the query is better.
