### ISSUE TITLE
Bug: unsupported operand for lambda

### ISSUE THREAD

**Issue by bpereto** [jolt-org/advanced-alchemy#64]
### Description

Using the latest version, I encounter the following error:
```
advanced_alchemy/repository/_async.py", line 1225, in _filter_by_where
    statement += lambda s: s.where(field == value)
TypeError: unsupported operand type(s) for +=: 'Select' and 'function'
```

https://github.com/jolt-org/advanced-alchemy/blob/f40e497feb098ace05bfbc87a332b7dd4597f97d/advanced_alchemy/repository/_async.py#L1216
```
    def _filter_by_where(
        self,
        statement: StatementLambdaElement,
        field_name: str | InstrumentedAttribute,
        value: Any,
    ) -> StatementLambdaElement:
        field = get_instrumented_attr(self.model_type, field_name)
        statement += lambda s: s.where(field == value)
        return statement
```

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Jolt Project Version

0.3.4

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jolt-org/advanced-alchemy/issues/64">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/64/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/64/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
Can you share any additional details about the query you were executing or how I can reproduce this?

**Comment by bpereto** [comment]
ok, got the error.

specified some weird statement, which is already defined in the service:
```
async def provide_customer_service(db_session: AsyncSession) -> AsyncGenerator[CustomerService, None]:
    """Construct repository and service objects for the request."""
    from app.domain.customers.models import Customer

    async with CustomerService.new(
        session=db_session, statement=select(Customer).options(selectinload(Customer.transactions).noload("*"))
    ) as service:
        yield service
        
        
class CustomerController(Controller):
    @get(
        operation_id="GetCustomer",
        name="customers:get",
        path="/{customer_id:uuid}",
        cache=False,
        summary="Retrieve the details of a customer.",
    )
    async def get_customer(
        self,
        customers_service: CustomerService,
        customer_id: UUID = Parameter(
            title="Customer ID",
            description="The customer to retrieve.",
        ),
    ) -> Customer:
customers_service.repository.statement = customers_service.repository.statement.options(
selectinload(Customer.transactions).noload("*")

db_obj = await customers_service.get(customer_id)
        return customers_service.to_dto(db_obj)
 )
 
 ```
 
 removing `customers_service.repository.statement = customers_service.repository.statement.options(
selectinload(Customer.transactions).noload("*")` resolved it.

**Comment by cofin** [comment]
I see.  I think by the time `repository.statement` is set, it's already a `LambdaStatement` instead of a `select`.  Let me know if you see any other strangeness on this.
