### ISSUE TITLE
Enhancement: litestar `create_all` config attribute

### ISSUE THREAD

**Issue by peterschutt** [jolt-org/advanced-alchemy#65]
### Summary

We can probably abstract the:

```py
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
```
boilerplate away.

### Basic Example

```py
db_config = SQLAlchemyAsyncConfig(connection_string="sqlite+aiosqlite:///todo.sqlite", create_all=metadata)
```

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jolt-org/advanced-alchemy/issues/65">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/65/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/65/pledge.svg">
</picture>
</a>

**Comment by Oakington** [comment]
If we're using multiple databases [eg](https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.AsyncSession.get_bind), is there a way to utilize this shortcut? or does one need to do a 
```python
async with engines[Base.__bind_key__].begin() as conn:
    await conn.run_sync(Base.metadata.create_all)
```
for each DB?

**Comment by cofin** [comment]
> If we're using multiple databases [eg](https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.AsyncSession.get_bind), is there a way to utilize this shortcut? or does one need to do a
> 
> ```python
> async with engines[Base.__bind_key__].begin() as conn:
>     await conn.run_sync(Base.metadata.create_all)
> ```
> 
> for each DB?

I think this is currently the only way.  I don't think I considered this when implementing it.  

Feel free to make a new issue for the feature enhancement and I can try to work it in later on (or you can make the PR as well, I'd be happy to accept it)
