### ISSUE TITLE
Enhancement: Add `match_fields` to `upsert` and `upsert_many`

### ISSUE THREAD

**Issue by JacobCoffee** [jolt-org/advanced-alchemy#73]
### Summary

https://github.com/jolt-org/advanced-alchemy/blob/090725a9a8e9a598d52b370766ff30aca073b022/advanced_alchemy/service/_sync.py#L403 would benefit from a `match_fields` so that we do not have to use something like `get_or_upsert` with a loop to update in bulk

**Comment by cofin** [comment]
`upsert` should be added to this as well.
